### ISSUE TITLE
No English locale strings can not be correctly displayed.

### ISSUE THREAD

**Issue by charset** [jewalky/UnityAllods#5]
I have a Triditional Chinese game client but all Chinese Characters are displayed wrong.
For example: 
`Assets/GameLogic/Structure/ShopScreen.cs #415`  .
```csharp
 o_ButtonTextRenderers[0].Text = string.Format("{0}\n{1}", Locale.Main[72], ItemView.FormatMoney(Unit.Player.Money));
```
We know the strings are displayed via `AllodsTextRenderer`, which `Fonts.Font4` is the parameter for `font`.
But `Font4` has only 224 entries and no other characters to display.

**Comment by anotomix** [comment]
Make own chinese font, no?

**Comment by charset** [comment]
> Make own chinese font, no?

OK. would look into this .
