### ISSUE TITLE
NullReferenceException: Object reference not set to an instance of an object MouseCursor.OnPreRenderCursor

### ISSUE THREAD

**Issue by YunusOzdemirr** [jewalky/UnityAllods#6]
Hi the project is not running I am getting so many error can you check or help me?

Maybe you can create a tutorial video on youtube about the running this project on unity

NullReferenceException: Object reference not set to an instance of an object
MouseCursor.OnPreRenderCursor () (at Assets/MouseCursor.cs:152)
MainCamera.OnPreRender () (at Assets/MainCamera.cs:201)

also this error

Abort: Couldn't load "graphics/cursors/default/sprites.16a"
Stack trace:System.Exception: Exception of type 'System.Exception' was thrown.

UnityEngine.Debug:LogErrorFormat(String, Object[])
Core:Abort(String, Object[]) (at Assets/Data/Core.cs:15)
Images:Load16A(String, Boolean) (at Assets/Data/Images.cs:588)
Images:LoadSprite(String) (at Assets/Data/Images.cs:836)
MouseCursor:CreateCursor(String, Int32, Int32, Single) (at Assets/MouseCursor.cs:48)
MouseCursor:Start() (at Assets/MouseCursor.cs:111)

**Comment by anotomix** [comment]
Please check readme file first, to run project:

**You will need the RES files from ROM2 installation in the root directory.**

**Comment by YunusOzdemirr** [comment]
okey that is solved but i have another question,
Is this project running on rom1?

**Comment by anotomix** [comment]
Nope
